export const items = [
    { id: 0, type: 'sword', name: 'sword of valor' },
    { id: 1, type: 'sword', name: 'sword of valor' },
    { id: 2, type: 'sword', name: 'sword of valor' },
    { id: 3, type: 'sword', name: 'sword of valor' },
    { id: 4, type: 'sword', name: 'sword of valor' },
    { id: 5, type: 'sword', name: 'sword of valor' },
    { id: 6, type: 'sword', name: 'sword of valor' },
    { id: 7, type: 'sword', name: 'sword of valor' },
    { id: 8, type: 'sword', name: 'sword of valor' },
    { id: 9, type: 'sword', name: 'sword of valor' },
    { id: 10, type: 'sword', name: 'sword of valor' },
    { id: 11, type: 'sword', name: 'sword of valor' },
    { id: 12, type: 'sword', name: 'sword of valor' },
    { id: 13, type: 'sword', name: 'sword of valor' },
    { id: 14, type: 'sword', name: 'sword of valor' },
    { id: 15, type: 'sword', name: 'sword of valor' },
    { id: 16, type: 'sword', name: 'sword of valor' },
    { id: 17, type: 'sword', name: 'sword of valor' },
    { id: 18, type: 'sword', name: 'sword of valor' },
    { id: 19, type: 'sword', name: 'sword of valor' },
    { id: 20, type: 'sword', name: 'sword of valor' },
    { id: 21, type: 'sword', name: 'sword of valor' },
    { id: 22, type: 'sword', name: 'sword of valor' },
    { id: 23, type: 'sword', name: 'sword of valor' },
]